1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin

2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)

4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 
9 değer) 3x3 shape'inde bir matris oluşturun.

6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)

8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [6]:
import numpy as np

In [66]:
# 1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin

arry = np.array([[[0,1,2],[3,4,5],[6,7,8]]])
print(arry.ndim)
print(arry.shape)

3
(1, 3, 3)


In [65]:
# 2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

arry = np.arange(34,113,6)
print(arry.ndim)
print(arry.shape)

1
(14,)


In [72]:
#3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)

arry = np.random.default_rng().integers(low=50, high=501, size=391)
arry = np.linspace(start=50, stop=500, num=391,  dtype=int)
print(arry.ndim)
print(arry.shape)
print(max(arry))
print(min(arry))
print(len(arry))

1
(391,)
500
50
391


In [62]:
# 4) 100(102) ile 10000(105) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

arry = np.logspace(start=2, stop=4, num=8)
print(arry.ndim)
print(arry.shape)
print(arry)
print(len(arry))

1
(8,)
[  100.           193.06977289   372.75937203   719.685673
  1389.49549437  2682.69579528  5179.47467923 10000.        ]
8


In [63]:
# 5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.

arry = np.linspace(start=0, stop=8, num=9,  dtype=int).reshape(3,3)
print(arry.ndim)
print(arry.shape)
print(arry)

2
(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [67]:
# 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

arry = np.linspace(start=0, stop=35, num=36,  dtype=int).reshape(6,6)
print(arry.ndim)
print(arry.shape)
print(arry)

2
(6, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [68]:
# 7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)

arry = np.linspace(start=0, stop=15, num=16,  dtype=int).reshape(4,4)
print(arry.ndim)
print(arry.shape)
print(arry)

2
(4, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [154]:
# 8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

arry = np.identity(8) #np.eye
print(arry.ndim)
print(arry.shape)
print(arry)
print(arry.dtype)
arry = arry.astype("int")
print(arry.dtype)



2
(8, 8)
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
float64
int64


In [71]:
# 9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

arry = np.identity(5) * 3
print(arry.ndim)
print(arry.shape)
print(arry)

2
(5, 5)
[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]]


In [78]:
# 10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

arry = np.random.rand(6)
print(arry.ndim)
print(arry.shape)
print(max(arry))
print(min(arry))
print(len(arry))
print(arry)

1
(6,)
0.843976605340526
0.16231986279834765
6
[0.75315407 0.16231986 0.72407545 0.6485388  0.41004062 0.84397661]


In [135]:
# 11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

arry = np.random.rand(10).reshape(5,2)*50+50 # np.random.rand(5,2) / randint(50,100,10).reshape(5,2) / randint(50,100,(5,2))
print(arry.ndim)
print(arry.shape)
print(arry)

2
(5, 2)
[[56.74523779 60.21579611]
 [66.29951856 52.97840433]
 [79.22895457 65.45300043]
 [84.12397576 73.24323125]
 [52.98369579 94.08575883]]


In [94]:
#12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

arry = np.random.rand(50).reshape(2,5,5)*1000+100
print(arry.ndim)
print(arry.shape)
print(arry)

3
(2, 5, 5)
[[[1090.01496893  219.61264692 1022.51271027  732.52106212 1039.00478488]
  [ 793.47468363  573.44397709  883.91024189  796.90840896  870.88541132]
  [ 543.18683634  224.03949503  958.47113921  374.48046933  771.17870194]
  [ 664.48706999  572.98887357  683.43314562  274.77459673  546.32152867]
  [ 850.34405951  631.31079266  788.28344972  491.68527786  302.64231628]]

 [[1090.05657903  296.8903968   580.1178446   644.97720242  491.02428379]
  [ 283.11528604  186.28931113  369.54969373  485.44366569  151.02170233]
  [ 173.13653101  613.15097254  684.89766032  358.89774061  388.27556756]
  [ 104.69965005  566.69586317  902.93535392 1002.73650828  876.59998856]
  [ 237.98943743  661.36055996  942.59858392  850.66063215  282.52859726]]]


In [98]:
# 13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

arry = np.random.default_rng().integers(low=0, high=101, size=10)
print(arry.ndim)
print(arry.shape)
print(max(arry))
print(min(arry))
print(len(arry))

1
(10,)
94
14
10


In [148]:
# 14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

arry = np.random.default_rng().integers(low=300, high=501, size=20).reshape(2,2,5)
#print(arry.ndim)
#print(arry.shape)
print(arry)

min=99999
max = 0

for i in arry:
  for j in i:
    for k in j:
      if k > max:
        max = k
      if k < min:
        min = k

print(np.amin(arry))
print(np.amax(arry))
print(min)
print(max)
i_min == np.where(arry == min)
i_max == np.where(arry == max)

print(f"index of min : {i_min}")
print(f"index of max : {i_max}")

print(np.min(arry))
print(np.max(arry))

print(np.argmin(arry))
print(np.argmax(arry))

[[[350 363 366 461 321]
  [453 494 414 351 467]]

 [[409 310 497 410 396]
  [386 458 313 360 318]]]
310
497
310
497
index of min : (array([1]), array([1]), array([1]))
index of max : (array([0]), array([1]), array([1]))
310
497
11
12


In [131]:
# 15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

arry = np.linspace(start=0, stop=50, num=51,  dtype=int)
print(arry)

arry[20:36] = 500
print(arry)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50]
