# Ödev 1

1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin

2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)

4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 
9 değer) 3x3 shape'inde bir matris oluşturun.

6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)

8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [ ]:
import numpy as np

In [ ]:
# 1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin

arry = np.array([[[0,1,2],[3,4,5],[6,7,8]]])
print(arry.ndim)
print(arry.shape)

3
(1, 3, 3)


In [ ]:
# 2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

arry = np.arange(34,113,6)
print(arry.ndim)
print(arry.shape)

1
(14,)


In [ ]:
#3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)

arry = np.random.default_rng().integers(low=50, high=501, size=391)
arry = np.linspace(start=50, stop=500, num=391,  dtype=int)
print(arry.ndim)
print(arry.shape)
print(arry.max)
print(arry.min)
print(len(arry))

1
(391,)
<built-in method max of numpy.ndarray object at 0x7f40a4ca1b70>
<built-in method min of numpy.ndarray object at 0x7f40a4ca1b70>
391


In [ ]:
# 4) 100(102) ile 10000(105) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

arry = np.logspace(start=2, stop=4, num=8)
print(arry.ndim)
print(arry.shape)
print(arry)
print(len(arry))

1
(8,)
[  100.           193.06977289   372.75937203   719.685673
  1389.49549437  2682.69579528  5179.47467923 10000.        ]
8


In [ ]:
# 5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.

arry = np.linspace(start=0, stop=8, num=9,  dtype=int).reshape(3,3)
print(arry.ndim)
print(arry.shape)
print(arry)

2
(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

arry = np.linspace(start=0, stop=35, num=36,  dtype=int).reshape(6,6)
print(arry.ndim)
print(arry.shape)
print(arry)

2
(6, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
# 7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)

arry = np.linspace(start=0, stop=15, num=16,  dtype=int).reshape(4,4)
print(arry.ndim)
print(arry.shape)
print(arry)

2
(4, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
# 8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

arry = np.identity(8) #np.eye
print(arry.ndim)
print(arry.shape)
print(arry)
print(arry.dtype)
arry = arry.astype("int")
print(arry.dtype)



2
(8, 8)
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
float64
int64


In [ ]:
# 9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

arry = np.identity(5) * 3
print(arry.ndim)
print(arry.shape)
print(arry)

2
(5, 5)
[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]]


In [ ]:
# 10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

arry = np.random.rand(6)
print(arry.ndim)
print(arry.shape)
print(arry.max())
print(arry.min())
print(len(arry))
print(arry)

1
(6,)
0.9074622894789531
0.018109987874447064
6
[0.71833139 0.01810999 0.90746229 0.79036799 0.7841565  0.38157784]


In [ ]:
# 11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

arry = np.random.rand(10).reshape(5,2)*50+50 # np.random.rand(5,2) / randint(50,100,10).reshape(5,2) / randint(50,100,(5,2))
print(arry.ndim)
print(arry.shape)
print(arry)

2
(5, 2)
[[93.92085461 56.45731291]
 [54.02452802 63.72689947]
 [54.89071742 68.77606595]
 [82.57266438 71.5385131 ]
 [69.2699156  95.33739984]]


In [ ]:
#12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

arry = np.random.rand(50).reshape(2,5,5)*1000+100
print(arry.ndim)
print(arry.shape)
print(arry)

3
(2, 5, 5)
[[[ 666.4113072   207.57942657  152.81871471  249.45817638 1094.14187126]
  [1067.88360691  762.76095066  542.07569975  257.52154929  415.93682019]
  [ 147.90675553 1041.68924242  636.83313051  489.29865174  825.45326556]
  [ 426.19603707  950.79226742  720.65345619  413.25729285  827.07913485]
  [ 265.87716342  868.8513029  1061.03813333  659.75422818  292.67416455]]

 [[ 994.45368872  233.26692164  822.32184122 1085.31804606  311.84449865]
  [ 274.638279   1010.59860031  758.69694387  195.07776077  473.61348823]
  [ 585.19257106  331.46762373 1036.75533598  457.78676723  523.8566314 ]
  [ 790.45185775  333.29581419  659.53221646  125.33509013  187.12510124]
  [ 670.18502004  927.54948744  673.40792273  575.46374416  149.17232513]]]


In [ ]:
# 13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

arry = np.random.default_rng().integers(low=0, high=101, size=10)
print(arry.ndim)
print(arry.shape)
print(arry.max())
print(arry.min())
print(len(arry))

1
(10,)
94
0
10


In [ ]:
# 14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

arry = np.random.default_rng().integers(low=300, high=501, size=20).reshape(2,2,5)
#print(arry.ndim)
#print(arry.shape)
print(arry)

min=99999
max = 0

for i in arry:
  for j in i:
    for k in j:
      if k > max:
        max = k
      if k < min:
        min = k

print(np.amin(arry))
print(np.amax(arry))
print(min)
print(max)
i_min = np.where(arry == min)
i_max = np.where(arry == max)

print(f"index of min : {i_min}")
print(f"index of max : {i_max}")

print(np.min(arry))
print(np.max(arry))

print(np.argmin(arry))
print(np.argmax(arry))

[[[310 494 412 311 311]
  [498 394 351 465 496]]

 [[362 434 410 396 301]
  [437 427 498 366 389]]]
301
498
301
498
index of min : (array([1]), array([0]), array([4]))
index of max : (array([0, 1]), array([1, 1]), array([0, 2]))
301
498
14
5


In [ ]:
# 15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

arry = np.linspace(start=0, stop=50, num=51,  dtype=int)
print(arry)

arry[20:36] = 500
print(arry)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50]


# Ödev 2

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.
2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.
5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.
6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.
7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.
8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.
9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.
10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.
11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.
12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.
13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.
14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.
15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin
16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.
17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.
18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [ ]:
# 1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin. 

arry = np.linspace(start=0, stop=29, num=30,  dtype=int).reshape(15,2)
print(arry)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]


In [ ]:
#2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

arry = np.linspace(start=0, stop=59, num=60,  dtype=int).reshape(2,6,-1)
print(arry.shape)
print(arry.ndim)

(2, 6, 5)
3


In [ ]:
#3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin. 

arry = np.random.randint(low=0, high=2,size=(4,5) , dtype = int)
arry.flatten
print(arry)
print(arry.shape)
print(arry.ndim)

[[0 1 0 1 0]
 [1 0 0 1 1]
 [0 0 1 0 1]
 [1 1 1 0 1]]
(4, 5)
2


In [ ]:
#4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın. 

arry = np.random.randint(low=0, high=2, size=(4,5), dtype = int)
print(arry)

# with for loop
for x in arry:
  for y in x:
    print(y)

# with nditer
for x in np.nditer(arry):
  print(x)

# with ndenumerate
for idx, x in np.ndenumerate(arry):
  print(idx, x)

[[0 1 1 1 0]
 [1 1 0 1 1]
 [1 1 0 1 0]
 [0 0 1 1 0]]
0
1
1
1
0
1
1
0
1
1
1
1
0
1
0
0
0
1
1
0
0
1
1
1
0
1
1
0
1
1
1
1
0
1
0
0
0
1
1
0
(0, 0) 0
(0, 1) 1
(0, 2) 1
(0, 3) 1
(0, 4) 0
(1, 0) 1
(1, 1) 1
(1, 2) 0
(1, 3) 1
(1, 4) 1
(2, 0) 1
(2, 1) 1
(2, 2) 0
(2, 3) 1
(2, 4) 0
(3, 0) 0
(3, 1) 0
(3, 2) 1
(3, 3) 1
(3, 4) 0


In [ ]:
#5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve 1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun. Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi. 

arry_1 = np.array([5,10,15,20,25,30])
arry_2 = np.array([1,2,3,4,5,6])

print(arry_1 + arry_2)
print(arry_1 - arry_2)
print(arry_1 * arry_2)
print(arry_1 / arry_2)
print(arry_1 ** arry_2)
print(np.dot(arry_1,arry_2))

boolean_array = arry_1 >= arry_2
print(boolean_array)

[ 6 12 18 24 30 36]
[ 4  8 12 16 20 24]
[  5  20  45  80 125 180]
[5. 5. 5. 5. 5. 5.]
[        5       100      3375    160000   9765625 729000000]
455
[ True  True  True  True  True  True]


In [ ]:
#6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin. 

arry = np.random.randint(low=0, high=101, size=(10), dtype = int)
print(arry.sum())
print(arry.min())
print(arry.max())
print(arry.mean())
print(arry.var())
print(arry.std())

573
7
84
57.3
536.01
23.151889771679546


In [ ]:
#7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın. 


arry_1 = np.linspace(start=0, stop=19, num=(20), dtype=int)
arry_2 = np.linspace(start=500, stop=530, num=31, dtype=int)

print(np.concatenate((arry_1, arry_2), axis=0))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515
 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530]


In [ ]:
#8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın. 

arry_1 = np.arange(start=15, stop=51,  dtype=int)
arry_2 = np.arange(start=10, stop=101, dtype=int)
arry_3 = np.concatenate((arry_1, arry_2), axis=0)
arry_3[25:51] = 888

for idx, x in np.ndenumerate(arry_3):
  print(idx, x)

(0,) 15
(1,) 16
(2,) 17
(3,) 18
(4,) 19
(5,) 20
(6,) 21
(7,) 22
(8,) 23
(9,) 24
(10,) 25
(11,) 26
(12,) 27
(13,) 28
(14,) 29
(15,) 30
(16,) 31
(17,) 32
(18,) 33
(19,) 34
(20,) 35
(21,) 36
(22,) 37
(23,) 38
(24,) 39
(25,) 888
(26,) 888
(27,) 888
(28,) 888
(29,) 888
(30,) 888
(31,) 888
(32,) 888
(33,) 888
(34,) 888
(35,) 888
(36,) 888
(37,) 888
(38,) 888
(39,) 888
(40,) 888
(41,) 888
(42,) 888
(43,) 888
(44,) 888
(45,) 888
(46,) 888
(47,) 888
(48,) 888
(49,) 888
(50,) 888
(51,) 25
(52,) 26
(53,) 27
(54,) 28
(55,) 29
(56,) 30
(57,) 31
(58,) 32
(59,) 33
(60,) 34
(61,) 35
(62,) 36
(63,) 37
(64,) 38
(65,) 39
(66,) 40
(67,) 41
(68,) 42
(69,) 43
(70,) 44
(71,) 45
(72,) 46
(73,) 47
(74,) 48
(75,) 49
(76,) 50
(77,) 51
(78,) 52
(79,) 53
(80,) 54
(81,) 55
(82,) 56
(83,) 57
(84,) 58
(85,) 59
(86,) 60
(87,) 61
(88,) 62
(89,) 63
(90,) 64
(91,) 65
(92,) 66
(93,) 67
(94,) 68
(95,) 69
(96,) 70
(97,) 71
(98,) 72
(99,) 73
(100,) 74
(101,) 75
(102,) 76
(103,) 77
(104,) 78
(105,) 79
(106,) 80
(107,) 81
(108

In [ ]:
#9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve 320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın. 

arry_1 = np.arange(start=0, stop=40,  dtype=int).reshape(8,5)
arry_2 = np.arange(start=320, stop=360, dtype=int).reshape(8,5)
arry_3 = np.concatenate((arry_1, arry_2), axis=0)
arry_4 = np.concatenate((arry_1, arry_2), axis=1)

print(arry_3.shape)
print("\n")
print(arry_4.shape)


(16, 5)


(8, 10)


In [ ]:
#10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın. 

#arry_5 = np.concatenate((arry_1, arry_2), axis=2)

arry_5 = np.stack((arry_1, arry_2),axis=0)
arry_6 = np.stack((arry_1, arry_2),axis=1)
arry_7 = np.stack((arry_1, arry_2),axis=2)

print(arry_5.shape)
print("\n")
print(arry_6.shape)
print("\n")
print(arry_7.shape)

(2, 8, 5)


(8, 2, 5)


(8, 5, 2)


In [ ]:
#11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun. 

arry = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])

print(arry) 
print("All index value of 5 is: ", np.where(arry == 5)[0]) 
print("First index value of 5 is: ",np.where(arry == 5)[0][0])
print("list: ", np.where(arry == 5))

[ 1 20 25  4  4  5  4  4  1  6  9 12  1  5]
All index value of 5 is:  [ 5 13]
First index value of 5 is:  5
list:  (array([ 5, 13]),)


In [ ]:
#12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun. 

print("All index value of even numbers: ", np.where(arry % 2 == 0)[0]) 

All index value of even numbers:  [ 1  3  4  6  7  9 11]


In [ ]:
#13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun. 

print("All index value of even numbers: ", np.where(arry > 4)[0]) 

All index value of even numbers:  [ 1  2  5  9 10 11 13]


In [ ]:
#14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.

print("All index value of numbers that divisible by 5 : ", np.where(arry // 5 == arry / 5)[0]) 
print("All index value of numbers that divisible by 5 : ", np.where(arry % 5 == 0)[0]) 

All index value of numbers that divisible by 5 :  [ 1  2  5 13]
All index value of numbers that divisible by 5 :  [ 1  2  5 13]


In [ ]:
#15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin 

#with np.random.randint / array
arry = np.random.randint(low=85, high=101, size=(1), dtype = int)

#with np.random.uniform / float
a = np.random.uniform(low=85, high=101, size=(1,))

#with np.random.randint / number
a = np.random.randint(85, 101)

print(a)

94


In [ ]:
#16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.

arry = np.random.uniform(low=10, high=100, size=(3,3))
print(arry)

[[96.00922987 81.21647889 79.42436648]
 [98.65782748 55.49974345 78.05957369]
 [75.23926646 99.25497263 89.48873178]]


In [ ]:
#17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin. 

arry = np.arange(start=35, stop=60, dtype=int)
choices = np.arange(start=0, stop=len(arry), dtype=int)

from random import randrange
# get random index number
i = randrange(len(arry))
item = arry[i]
# Select item using index number
print("Randomly selected item", arry[i], "is present at index:", i)

a = np.random.choice(arry)
print(a)

Randomly selected item 44 is present at index: 9
51


In [ ]:
#18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

choices = [3, 8, 10, 53]
arry = np.random.choice(choices, replace = True, size = 10).reshape(2,5)
print(arry)

[[ 3 53 10  8  3]
 [ 8  3 53 53 10]]
